### ISSUE TITLE
if the package can be applied to 10X scRNA-Seq data

### ISSUE THREAD

**Issue by zhumengyan** [diazlab/CONICS#6]
Dear soeren:
Thanks for providing the great package!
I have a problem, if your package can be applied to 10X scRNA-Seq data?

I really appreciate your help!
zhumengyan

**Comment by soerenmueller** [comment]
Hey zhumengyan, 
yes, CONICSmat does work with 10x data. I had posted an image from one of our datasets before in this thread:
https://github.com/diazlab/CONICS/issues/3

As you can see, we can identify 5 different clones in that specific 10x dataset from a treatment-resistant GBM. 

Cheers,
Soren

**Comment by kokonech** [comment]
Hi! The CONICSmat package is really perspective in my opinion, but I also have some questions regarding application on 10X. Are there some specific control settings that should be applied in this case? For example, I tried using it on our 10X tumor data samples in order to classify the cell types with CNV. For this I used log2 (CPM/10 + 1) from counts per cell and other settings as in the main tutorial. However, not much suitability to the bulk CNV control from 450K data was detected e.g. some losses were missed, additional gains detected that are not present in bulk.  Moreover, in the check for "BIC difference" nothing went higher than 50, while in the tutorials limit is set up to 200. Are there other settings that should be adjusted accordingly to 10X data?
